GET http://localhost:4020/voucher/

###
GET http://localhost:4020/user/


###
GET http://localhost:4020/voucher/getall/2

###
POST http://localhost:4020/user/signin
Content-Type: application/json

{
    "email": admazra@gmail.com,
    "password": rahasia
}

###
POST http://localhost:4020/trasaction/chechkout
Content-Type: application/json

{
    "verifyId": asdasd,
    "nameGame": namasdasdeGame,
    "payment": payasdsadment,
    "coin": asdasd,
}